### ISSUE TITLE
getting an issue in project1.py file

### ISSUE THREAD

**Issue by mayursd** [murtazahassan/Learn-OpenCV-in-3-hours#14]
Traceback (most recent call last):
  File "C:/Users/mayur/PycharmProjects/OpenCV projects/read.py", line 20, in <module>
    findColor ( img, mycolors )
  File "C:/Users/mayur/PycharmProjects/OpenCV projects/read.py", line 16, in findColor
    cv2.imshow(img,mask)
cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'imshow'
> Overload resolution failed:
>  - Can't convert object of type 'numpy.ndarray' to 'str' for 'winname'
>  - Can't convert object of type 'numpy.ndarray' to 'str' for 'winname'
>  - Can't convert object of type 'numpy.ndarray' to 'str' for 'winname'
![Screenshot (39)](https://user-images.githubusercontent.com/66072367/118521463-b1a02680-b758-11eb-834d-95193c66dfa2.png)

**Comment by mayursd** [comment]
my bad... It was syntax error
